// Writes src/lib/config.ts from the contracts package's chain config and deployment record.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = join(here, "..", "..", "contracts");
const chain = JSON.parse(readFileSync(join(contracts, "config", "4663.json"), "utf8"));
const deploymentsPath = join(contracts, "deployments", "4663.json");
const deployments = existsSync(deploymentsPath) ? JSON.parse(readFileSync(deploymentsPath, "utf8")) : { contracts: {} };
const address = (name) => deployments.contracts?.[name]?.address ?? "";

const out = `// Generated by scripts/sync-config.mjs. Do not edit by hand.
export const config = {
  chainId: ${chain.chainId},
  rpc: ${JSON.stringify(chain.rpc)},
  explorer: ${JSON.stringify(chain.explorer)},
  usdg: ${JSON.stringify(chain.usdg)},
  safe: "0xfCeB8905E316D383Cd90Aa1Ab04ab1650611445b",
  factory: ${JSON.stringify(address("BudgetAccountFactory"))},
  implementation: ${JSON.stringify(deployments.contracts?.BudgetAccountFactory?.implementation ?? "")},
  burnVault: ${JSON.stringify(address("BurnVault"))},
  registry: ${JSON.stringify(address("CreatorRegistry"))},
  verifierApi: "/api",
} as const;
`;
mkdirSync(join(here, "..", "src", "lib"), { recursive: true });
writeFileSync(join(here, "..", "src", "lib", "config.ts"), out);
console.log("wrote src/lib/config.ts");
