export const LINKS = {
  site: "https://payhole.org",
  extension: "https://payhole.org/extension.html",
  sinkhole: "https://payhole.org/sinkhole.html",
  blog: "https://payhole.org/blog/",
  privacy: "https://payhole.org/privacy.html",
  github: "https://github.com/S4PAY/payhole",
  x: "https://x.com/payhole_x402",
  dohUrl: "https://dns.payhole.org/dns-query",
  verdictUrl: "https://dns.payhole.org/verdict",
  radarUrl: "https://dns.payhole.org/radar",
  reportUrl: "https://dns.payhole.org/report",
  link: "https://payhole.org/link.html",
  radar: "https://payhole.org/radar.html",
  check: "https://payhole.org/check.html",
  reportEmail: "hello@payhole.org",
  dotHost: "dns.payhole.org",
} as const;
