# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classifier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'classifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63lassifier.proto\x12\x12payhole.classifier\"\xa7\x02\n\rFeatureVector\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12\x43\n\tnumerical\x18\x03 \x03(\x0b\x32\x30.payhole.classifier.FeatureVector.NumericalEntry\x12G\n\x0b\x63\x61tegorical\x18\x04 \x03(\x0b\x32\x32.payhole.classifier.FeatureVector.CategoricalEntry\x1a\x30\n\x0eNumericalEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a\x32\n\x10\x43\x61tegoricalEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"`\n\x15\x43lassificationRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x33\n\x08\x66\x65\x61tures\x18\x02 \x01(\x0b\x32!.payhole.classifier.FeatureVector\"a\n\x16\x43lassificationResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\r\n\x05label\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\t2n\n\nClassifier\x12`\n\x07Predict\x12).payhole.classifier.ClassificationRequest\x1a*.payhole.classifier.ClassificationResponseB-Z+github.com/payhole/ai/pkg/schema/classifierb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/payhole/ai/pkg/schema/classifier'
  _globals['_FEATUREVECTOR_NUMERICALENTRY']._loaded_options = None
  _globals['_FEATUREVECTOR_NUMERICALENTRY']._serialized_options = b'8\001'
  _globals['_FEATUREVECTOR_CATEGORICALENTRY']._loaded_options = None
  _globals['_FEATUREVECTOR_CATEGORICALENTRY']._serialized_options = b'8\001'
  _globals['_FEATUREVECTOR']._serialized_start=41
  _globals['_FEATUREVECTOR']._serialized_end=336
  _globals['_FEATUREVECTOR_NUMERICALENTRY']._serialized_start=236
  _globals['_FEATUREVECTOR_NUMERICALENTRY']._serialized_end=284
  _globals['_FEATUREVECTOR_CATEGORICALENTRY']._serialized_start=286
  _globals['_FEATUREVECTOR_CATEGORICALENTRY']._serialized_end=336
  _globals['_CLASSIFICATIONREQUEST']._serialized_start=338
  _globals['_CLASSIFICATIONREQUEST']._serialized_end=434
  _globals['_CLASSIFICATIONRESPONSE']._serialized_start=436
  _globals['_CLASSIFICATIONRESPONSE']._serialized_end=533
  _globals['_CLASSIFIER']._serialized_start=535
  _globals['_CLASSIFIER']._serialized_end=645
# @@protoc_insertion_point(module_scope)
