// Copies contract ABIs, the chain configuration, and the deployment record from packages/contracts into
// src/generated so the SDK builds and publishes without a Foundry toolchain.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = join(here, "..", "..", "contracts");
const outDir = join(here, "..", "src", "generated");
mkdirSync(outDir, { recursive: true });

const header = "// Generated by scripts/sync-abi.mjs from packages/contracts. Do not edit by hand.\n\n";
const names = ["BudgetAccount", "BudgetAccountFactory", "BurnVault", "CreatorRegistry"];

let abi = header;
for (const name of names) {
  const artifact = JSON.parse(readFileSync(join(contracts, "out", `${name}.sol`, `${name}.json`), "utf8"));
  const exportName = name.charAt(0).toLowerCase() + name.slice(1) + "Abi";
  abi += `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(outDir, "abi.ts"), abi);

const chain = JSON.parse(readFileSync(join(contracts, "config", "4663.json"), "utf8"));
writeFileSync(join(outDir, "chain.ts"), `${header}export const chainConfig = ${JSON.stringify(chain, null, 2)} as const;\n`);

const deploymentsPath = join(contracts, "deployments", "4663.json");
const deployments = existsSync(deploymentsPath) ? JSON.parse(readFileSync(deploymentsPath, "utf8")) : { chainId: 4663, contracts: {} };
writeFileSync(join(outDir, "deployments.ts"), `${header}export const deployments = ${JSON.stringify(deployments, null, 2)} as const;\n`);

console.log(`generated ${names.length} ABIs, chain config, and deployments into src/generated`);
