// Signs release builds with the Play upload key when PAYHOLE_UPLOAD_* is set in the environment,
// and with the debug key otherwise, so a local build never needs the keystore. The native project is
// regenerated by prebuild, which is why this lives in a config plugin instead of build.gradle.
const { withAppBuildGradle } = require("expo/config-plugins");

const RELEASE_CONFIG = `        release {
            def uploadStore = System.getenv("PAYHOLE_UPLOAD_STORE_FILE")
            if (uploadStore) {
                storeFile file(uploadStore)
                storePassword System.getenv("PAYHOLE_UPLOAD_STORE_PASSWORD")
                keyAlias System.getenv("PAYHOLE_UPLOAD_KEY_ALIAS")
                keyPassword System.getenv("PAYHOLE_UPLOAD_KEY_PASSWORD")
            }
        }
`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    let gradle = mod.modResults.contents;
    if (!gradle.includes("PAYHOLE_UPLOAD_STORE_FILE")) {
      const debugBlock = /    signingConfigs \{\n        debug \{[\s\S]*?\n        \}\n/;
      if (!debugBlock.test(gradle)) throw new Error("withReleaseSigning: signingConfigs.debug block not found in app/build.gradle");
      gradle = gradle.replace(debugBlock, (block) => block + RELEASE_CONFIG);
      // Only the release build type changes; the signingConfigs block above also has a "release {" line.
      const buildTypesAt = gradle.indexOf("    buildTypes {");
      if (buildTypesAt < 0) throw new Error("withReleaseSigning: buildTypes block not found in app/build.gradle");
      const head = gradle.slice(0, buildTypesAt);
      let tail = gradle.slice(buildTypesAt);
      const releaseSigning = /(        release \{\n(?:.*\n)*?)            signingConfig signingConfigs\.debug\n/;
      if (!releaseSigning.test(tail)) throw new Error("withReleaseSigning: release signingConfig line not found in app/build.gradle");
      tail = tail.replace(releaseSigning, '$1            signingConfig System.getenv("PAYHOLE_UPLOAD_STORE_FILE") ? signingConfigs.release : signingConfigs.debug\n');
      gradle = head + tail;
      mod.modResults.contents = gradle;
    }
    return mod;
  });
};
